client/src/App.css, client/src/App.js, client/src/component/MilestoneTable.js, client/src/component/User.js, client/src/pages/Home.css, client/src/pages/Home.js
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME
Write a summary of your change. Explain why you have made it.
Fixes #1
=> extra code has been deleted and to component add for display page

client/src/component/MilestoneTable.js, client/src/styles/MilestoneTable.css
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME
mobile-v 
Fixes #1
=> Milestone tabale with css created(hard-code)-mobie-v

client/src/component/User.css, client/src/component/User.js
used Prettier
fixing css style
removed unused code
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME
Write a summary of your change. Explain why you have made it.
Fixes #1
- [+ ] My code follows the style guidelines of this project
- [ +] I have carefully reviewed my own code
- [+ ] I have commented my code
=> cleaned code

client/src/component/Search.js
i created a search component to get data from codewars and github , also I use context to get userName value and  change the value of codewarsData and githubData
Fixes #22
=> #22-search component and  fetch Data-Boshra

client/src/component/Search.js, client/src/component/User.js, client/src/pages/Home.js
To run the code minor errors should be fixed :
1. In Home.js [Home.js](https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/blob/main/client/src/pages/Home.js) line#2 should be changed by: import { User } from "../component/User"; @Zobeir-Rigi 
2. In  [Search.js](https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/blob/main/client/src/component/Search.js) line#3 should be changed by: import { AppContext } from "../AppContext"; @BoshraM
=> #27-Importing Search Component into User Component-Olena

server/app.js, server/controllers/cohortController.js, server/controllers/traineeController.js, server/routes/cohortRoutes.js, server/routes/traineeRoutes.js
routes
the new route files created as we were face problem to who wher should write a code and who first send the pull request . we find this way easier to divided issues 
Fixes #36
=> controller and routes filles added-Boshra

server/controllers/traineeController.js, server/routes/traineeRoutes.js
I am not sure if the way I write these  two endpoint separately is good or not . we  need to use search endpoint when the trainees search for their milestone , I haven't connect this end point with data base ? may I add data base as well so when trainee see their dashboard we can  add some information from data base to dashboard for example which cohort they or which full name they have been registered?
we  need to use get endpoint with id  when product manager wants to view trainee information as I am not sure yet what we want to show them in this point ? 
related #30 
Fixes #30
=> two endpoints added to get and search  one trainee

server/controllers/cohortController.js, server/routes/cohortRoutes.js
Created Post Api to add a new cohort and update Api to update it, and also find a cohort by Id and return all trainees from the cohort. I tried to handle errors in two ways server-side & client-side.  
[Issue](https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/issues/34)
Fixes #1
=> #34-Add new cohort find cohort by id-Zobeir Rigi

migrations/1688509079773_init.js, package-lock.json, package.json
installed node-pg-migration for Postgresql
created migration.js for the project database
[node-pg-migrate](https://github.com/salsita/node-pg-migrate)
=> 47-Node.js database migration for Postgresql-Olena

client/src/App.js, client/src/pages/AddTrainee.js, client/src/pages/GetCohortById.js, client/src/pages/UpdateTrainee.js, server/controllers/cohortController.js, server/controllers/traineeController.js
Created a UpdatePage to edit each trainee's details, Added an edit link to each row, and then click its lunch to update the page, and when we submit and if there is no problem it navigates to a page back navigate (-1), has to install material UI or fontawesome to put icons instead of text. I like to edit trainees' details on the GetCohortById page instead of creating a new page for it but don't know how can I do that, maybe a goal for later.
crea
[Ticket](https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/issues/53)
Fixes #1
=> #53-add edit link to each row of trainees-Zobeir-Rigi

client/src/component/CodeWarsCard.js, client/src/component/DashboardHero.js, client/src/pages/Dashboard.js
Dashboard tested, hard code is done
=> 67-Hard coding Dashboard for User-Olena

client/src/App.js, client/src/component/DashboardHero.js, client/src/pages/Dashboard.js
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME
Write a summary of your change. Explain why you have made it.
Fixes #1
=> connecting dashboard page

client/src/component/CircleChart.js, client/src/pages/Dashboard.js, package-lock.json, package.json
I added a new library for pie chart
Please run **npm install recharts**
[more about recharts](https://recharts.org/en-US/guide)
[and here](https://recharts.org/en-US/examples/PieChartWithPaddingAngle)
=> 78-Finding pie chart package and creating component for it-Olena

client/src/pages/Dashboard.js
=> 26-getData function created and data passed-Boshra

client/src/component/DashboardHero.js
Create dashboard Hero-completed
Fixes #1
=> creating- Welcoming- component-Mohammad

client/src/styles/global.css
=> Update global css-Mohammad

client/src/component/Milestones.js, client/src/component/Search.js, client/src/component/User.css, client/src/component/User.js, client/src/pages/AddTrainee.js, client/src/pages/Home.js, client/src/pages/addTrainee.css
Only Cyf user should check their milestone so if you are not in the Cyf clan, it errors and cant go further, also Milestone.js file is modified.
[Ticket](https://github.com/BoshraM/ldn9-Ctrl-Shift-Learn/issues/77)
Fixes #1
=> #77-Error handling userSearch homePage-Zobeir-Rigi

client/src/component/MilestoneCard.js, client/src/component/milestoneCard.css, client/src/styles/global.css
we need to centre circle progress bar in   recharts-responsive-container
=> 92-Adding design to dashboard-Olena

client/data/milestones.json, client/src/component/MilestoneCard.js, client/src/pages/Dashboard.js
the new condition added to check if current date is before journey or is at the end
fixed #104
=> 104 make a difference when there is no milestone for trainee in dashboard

client/src/component/Footer.css
=> Update Footer css-Mohammad

client/src/component/DashboardHero.js, client/src/component/dashboardHero.css, client/src/pages/Dashboard.js
=> 120 boshra fixing design for dashboard hero

client/src/component/CircleChart.js, client/src/component/MilestoneCard.js, client/src/component/milestoneCard.css
Pull Request were changed into PRs in MilestoneCard
=> 108-Correctig start point of pie chart-Olena

client/src/component/Footer.css, client/src/component/Footer.js, client/src/component/Header.js, client/src/component/Search.js, client/src/component/User.css, client/src/component/User.js, client/src/component/header.css
footer p tag changed as changed all dashboard font color
Fixes #1
=> #119-make header responsive and change footer p tag-Zobeir-Rigi

client/src/component/CircleChart.js, client/src/component/DashboardHero.js, client/src/component/dashboardHero.css
=> 107-Adding desktop query for dashboard hero-Olena
